### ISSUE TITLE
Does not work with new update on 9/22

### ISSUE THREAD

**Issue by ResidentSoap** [wmtorode/MW5-SaveEditor#4]

**Comment by wmtorode** [comment]
What exactly is the issue? I managed to load a new save and existing career saves into the editor without issue with the new update and DLC. have any logs to go on?

**Comment by JHNewton** [comment]
I'm unable to save after adding anything.  Tells me that it is unable to write the files.

**Comment by wmtorode** [comment]
going to need logs or the save that replicates as it seems to work on my end

**Comment by JHNewton** [comment]
It seems to have been a one-time hiccup.  It has worked flawlessly since.

Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

Do not condemn the judgment of another because it differs from your own.
You may both be wrong. -Dandamis, sage (4c BCE)
